# Generated by Django 5.0.7 on 2024-07-25 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_id", models.PositiveBigIntegerField(unique=True)),
                ("status", models.CharField(max_length=20)),
                ("service", models.CharField(blank=True, max_length=20, null=True)),
                ("vip", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="SaleVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("automobile", models.CharField(max_length=200)),
                ("salesperson", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                ("import_id", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="billing_rest.salevo",
                    ),
                ),
            ],
        ),
    ]
