# Generated by Django 5.0.7 on 2024-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_rest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salevo",
            name="import_href",
        ),
        migrations.AddField(
            model_name="salevo",
            name="import_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
