# Generated by Django 5.0.7 on 2024-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_rest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("parts_cost", models.PositiveIntegerField()),
                ("labor_cost", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
