# Generated by Django 5.0.7 on 2024-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_rest", "0002_remove_salevo_import_href_salevo_import_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentvo",
            name="import_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
