# Generated by Django 5.0.7 on 2024-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_rest", "0003_appointmentvo_import_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentvo",
            name="vip",
            field=models.CharField(max_length=5),
        ),
    ]
