# Generated by Django 5.0.7 on 2024-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_rest", "0004_alter_appointmentvo_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentvo",
            name="service",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
